name: Docker CI

on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Dockerhub Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract repository name
      id: extract_repo
      run: |
        REPO_NAME=${GITHUB_REPOSITORY##*/}
        echo "REPO_NAME=${REPO_NAME,,}" >> $GITHUB_ENV

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.4.0
      with:
        context: .
        file: EmployeeSharp.Web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
